// Language.swift
// Supported languages for iControlBell

enum Language: String, CaseIterable, Identifiable {
    case english = "en"
    case spanish = "es"
    case french = "fr"
    case german = "de"
    case portuguese = "pt"
    case italian = "it"
    case japanese = "ja"
    case dutch = "nl"
    case russian = "ru"
    case chinese = "zh"
    case hindi = "hi"
    case arabic = "ar"
    case bengali = "bn"
    case korean = "ko"
    case turkish = "tr"
    case polish = "pl"
    case swedish = "sv"
    case vietnamese = "vi"
    case indonesian = "id"
    case urdu = "ur"
    case tagalog = "tl"
    case thai = "th"
    case greek = "el"
    case czech = "cs"
    case hungarian = "hu"
    case romanian = "ro"
    case danish = "da"
    case finnish = "fi"
    var id: String { rawValue }
    var displayName: String {
        switch self {
        case .english: return "English"
        case .spanish: return "Español"
        case .french: return "Français"
        case .german: return "Deutsch"
        case .portuguese: return "Português"
        case .italian: return "Italiano"
        case .japanese: return "日本語"
        case .dutch: return "Nederlands"
        case .russian: return "Русский"
        case .chinese: return "中文"
        case .hindi: return "हिन्दी"
        case .arabic: return "العربية"
        case .bengali: return "বাংলা"
        case .korean: return "한국어"
        case .turkish: return "Türkçe"
        case .polish: return "Polski"
        case .swedish: return "Svenska"
        case .vietnamese: return "Tiếng Việt"
        case .indonesian: return "Bahasa Indonesia"
        case .urdu: return "اردو"
        case .tagalog: return "Tagalog"
        case .thai: return "ภาษาไทย"
        case .greek: return "Ελληνικά"
        case .czech: return "Čeština"
        case .hungarian: return "Magyar"
        case .romanian: return "Română"
        case .danish: return "Dansk"
        case .finnish: return "Suomi"
        }
    }
}
